In [1]:
%matplotlib inline
import os
from IPython.display import Image
from IPython.display import display
import numpy as np
import pandas as pd
from scipy import interp
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import auc, confusion_matrix,  f1_score, precision_score, recall_score, roc_curve
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from cycler import cycler
import matplotlib
matplotlib.rcParams.update({'font.size': 22})
plt = matplotlib.pyplot

### Create team

In [2]:
df_team = pd.read_csv("team\\team_en.csv")

In [3]:
df_team

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,xG,xGA,xGD,xGD/90,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Manchester City,38,27,5,6,83,32,51,86,73.3,31.4,42.0,1.10,526,İlkay Gündoğan - 13,Ederson,→ UEFA Champions League via league finish
1,2,Manchester Utd,38,21,11,6,73,44,29,74,60.2,42.2,18.0,0.47,526,Bruno Fernandes - 18,David de Gea,→ UEFA Champions League via league finish
2,3,Liverpool,38,20,9,9,68,42,26,69,72.6,45.3,27.3,0.72,837,Mohamed Salah - 22,Alisson,→ UEFA Champions League via league finish
3,4,Chelsea,38,19,10,9,58,36,22,67,64.0,32.8,31.2,0.82,526,Jorginho - 7,Edouard Mendy,→ UEFA Champions League via league finish
4,5,Leicester City,38,20,6,12,68,50,18,66,56.0,47.7,8.3,0.22,421,Jamie Vardy - 15,Kasper Schmeichel,→ UEFA Europa League via cup win
5,6,West Ham,38,19,8,11,62,47,15,65,53.9,48.3,5.6,0.15,632,"Tomáš Souček, Michail Antonio - 10",Łukasz Fabiański,→ UEFA Europa League via league finish
6,7,Tottenham,38,18,8,12,68,45,23,62,54.5,49.5,5.0,0.13,632,Harry Kane - 23,Hugo Lloris,→ UEFA Europa Conference League via league fin...
7,8,Arsenal,38,18,7,13,55,39,16,61,53.5,44.3,9.2,0.24,632,Alexandre Lacazette - 13,Bernd Leno,NaN
8,9,Leeds United,38,18,5,15,62,54,8,59,57.5,62.9,-5.4,-0.14,421,Patrick Bamford - 17,Illan Meslier,NaN
9,10,Everton,38,17,8,13,47,48,-1,59,47.2,51.2,-4.1,-0.11,368,Dominic Calvert-Lewin - 16,Jordan Pickford,NaN
10,11,Aston Villa,38,16,7,15,55,46,9,55,52.9,52.9,0.1,0.00,526,Ollie Watkins - 14,Emiliano Martínez,NaN
11,12,Newcastle Utd,38,12,9,17,46,62,-16,45,41.0,54.0,-13.0,-0.34,526,Callum Wilson - 12,Karl Darlow,NaN
12,13,Wolves,38,12,9,17,36,52,-16,45,39.9,45.9,-6.0,-0.16,237,"Rúben Neves, Pedro Neto - 5",Rui Patrício,NaN
13,14,Crystal Palace,38,12,8,18,41,66,-25,44,32.4,57.5,-25.0,-0.66,447,Wilfried Zaha - 11,Vicente Guaita,NaN
14,15,Southampton,38,12,7,19,47,68,-21,43,42.4,54.2,-11.8,-0.31,526,Danny Ings - 12,Alex McCarthy,NaN
15,16,Brighton,38,9,14,15,40,46,-6,41,51.6,37.7,13.9,0.37,523,Neal Maupay - 8,Robert Sánchez,NaN
16,17,Burnley,38,10,9,19,33,55,-22,39,39.9,57.6,-17.7,-0.47,178,Chris Wood - 12,Nick Pope,NaN
17,18,Fulham,38,5,13,20,27,53,-26,28,40.5,53.0,-12.5,-0.33,211,Bobby Reid - 5,Alphonse Areola,Relegated
18,19,West Brom,38,5,11,22,35,76,-41,26,33.8,67.7,-34.0,-0.89,283,Matheus Pereira - 11,Sam Johnstone,Relegated
19,20,Sheffield Utd,38,7,2,29,20,63,-43,23,31.4,62.4,-31.0,-0.82,263,David McGoldrick - 8,Aaron Ramsdale,Relegated

In [4]:
df_team.values[:,1]

array(['Manchester City', 'Manchester Utd', 'Liverpool', 'Chelsea',
       'Leicester City', 'West Ham', 'Tottenham', 'Arsenal',
       'Leeds United', 'Everton', 'Aston Villa', 'Newcastle Utd',
       'Wolves', 'Crystal Palace', 'Southampton', 'Brighton', 'Burnley',
       'Fulham', 'West Brom', 'Sheffield Utd'], dtype=object)

### Create player dataset

In [5]:
from glob import glob
files = glob("player_data/*.csv")

In [6]:
test=pd.read_csv(files[9])
pd.read_csv(files[9])

,Unnamed: 0,Age,Squad,Country,Comp,LgRank,90s,Cmp,Att,Cmp%,...,PrgDist.1,Prog.1,1/3.1,CPA,Mis,Dis,Targ,Rec,Rec%,Prog.2
0,0,21,Chelsea,eng ENG,1. Premier League,4th,14.3,981,1098,89.3,...,2076,52,10,0,4,5,959,944,98.4,6
1,1,22,Chelsea,eng ENG,1. Premier League,4th,0.5,27,29,93.1,...,38,0,0,0,0,0,21,21,100.0,0
2,2,22,Milan,it ITA,1. Serie A,2nd,16.3,801,884,90.6,...,1605,26,7,0,4,2,717,705,98.3,3

In [7]:
test.values[:,6]

array([14.3, 0.5, 16.3], dtype=object)

In [8]:
len(files)

532

In [9]:
def one_player(df_one):
    df_num=df_one.shape[0]
    one_player=np.zeros((1, 71))
    for i in range(0,df_num):
    #print(i)
        if df_one.values[i,4]=='1. Premier League' :  # only collect the Premier Leage data
            dfxx= df_one.values[i,6:]           # collect the data after the column "LgRank"
            one_player=np.row_stack((one_player,dfxx))
            player_team_one= df_one.values[i,2]
        #if i==df_num-1:
         #   player_team_one= df_one.values[i,2]
    one_player=np.delete(one_player, 0, 0)     # delete temporay row
    #one_player=np.delete(one_player, 71-15, 1) # move the column have NAN
    one_player=np.mean(one_player,axis=0)      # average the data for different seasons
    return one_player,player_team_one

In [10]:
test.values[0,2]

'Chelsea'

In [11]:
player= np.zeros((1, 71))  #70 becuase that i delelete one NAN column
for i in range(0,532):   # 英超,532 players
    df_one = pd.read_csv(files[i])
    player_one,_= one_player(df_one)
    player= np.row_stack((player,player_one))
player=np.delete(player, 0, 0)     # delete temporay row

In [12]:
player.shape

(532, 71)

In [13]:
player_team= []  #70 becuase that i delelete one NAN column
for i in range(0,532):   # 英超,532 players
    df_one = pd.read_csv(files[i])
    _,player_team_one= one_player(df_one)
    player_team.append(player_team_one)

In [14]:
player_team

['Manchester City',
 'Manchester City',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Fulham',
 'Chelsea',
 'Chelsea',
 'Aston Villa',
 'Leicester City',
 'Manchester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Manchester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Manchester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'Manchester City',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'Manchester City',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Brom',
 'West Ham',
 'Manchester City',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Manchester City',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Manchester City',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Manchester City',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Manchester City',
 'Manchester City',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'West Brom',
 'Arsenal',
 'Arsenal',
 'Newcastle Utd',
 'Arsenal',
 'Manchester City',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Manchester City',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Manchester City',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Manchester City',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Manchester Utd',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Manchester Utd',
 'Everton',
 'Everton',
 'Southampton',
 'Everton',
 'Everton',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Manchester Utd',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Manchester Utd',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Newcastle Utd',
 'Manchester Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Manchester City',
 'Manchester Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Manchester Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Manchester Utd',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Manchester Utd',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Manchester Utd',
 'Wolves',
 'Wolves',
 'Wolves',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Manchester Utd',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Manchester Utd',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Southampton',
 'Southampton',
 'Southampton',
 'Manchester Utd',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Manchester Utd',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Manchester Utd',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Manchester City',
 'Manchester Utd',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Manchester Utd',
 'Arsenal',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Manchester Utd',
 'Brighton',
 'Brighton',
 'Brighton',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Manchester Utd',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Manchester Utd',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Fulham',
 'Fulham',
 'Manchester Utd',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Manchester Utd',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Manchester Utd',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'Manchester Utd',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'Manchester Utd',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'Manchester City',
 'Manchester Utd',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Manchester Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Manchester Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Manchester Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Manchester City',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Manchester City',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Southampton',
 'Liverpool',
 'Liverpool',
 'Manchester City',
 'Liverpool',
 'Liverpool',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Manchester City',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea']

In [15]:
len(player_team)

532

In [16]:
player_team

['Manchester City',
 'Manchester City',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Fulham',
 'Chelsea',
 'Chelsea',
 'Aston Villa',
 'Leicester City',
 'Manchester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Manchester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Manchester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'Leicester City',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'Manchester City',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'Manchester City',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Ham',
 'West Brom',
 'West Ham',
 'Manchester City',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Manchester City',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Manchester City',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Tottenham',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Manchester City',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Manchester City',
 'Manchester City',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'West Brom',
 'Arsenal',
 'Arsenal',
 'Newcastle Utd',
 'Arsenal',
 'Manchester City',
 'Arsenal',
 'Arsenal',
 'Arsenal',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Manchester City',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Manchester City',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Leeds United',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Manchester City',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Manchester Utd',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Everton',
 'Manchester Utd',
 'Everton',
 'Everton',
 'Southampton',
 'Everton',
 'Everton',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Manchester Utd',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Manchester Utd',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Aston Villa',
 'Newcastle Utd',
 'Manchester Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Manchester City',
 'Manchester Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Manchester Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Newcastle Utd',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Manchester Utd',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Manchester Utd',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Wolves',
 'Manchester Utd',
 'Wolves',
 'Wolves',
 'Wolves',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Manchester Utd',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Manchester Utd',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Crystal Palace',
 'Southampton',
 'Southampton',
 'Southampton',
 'Manchester Utd',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Manchester Utd',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Manchester Utd',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Southampton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Manchester City',
 'Manchester Utd',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Manchester Utd',
 'Arsenal',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Brighton',
 'Manchester Utd',
 'Brighton',
 'Brighton',
 'Brighton',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Manchester Utd',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Manchester Utd',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Burnley',
 'Fulham',
 'Fulham',
 'Manchester Utd',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Manchester Utd',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Manchester Utd',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'Fulham',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'Manchester Utd',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'Manchester Utd',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'Manchester City',
 'Manchester Utd',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'West Brom',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Manchester Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Manchester Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Manchester Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Sheffield Utd',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Manchester City',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Manchester City',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Liverpool',
 'Southampton',
 'Liverpool',
 'Liverpool',
 'Manchester City',
 'Liverpool',
 'Liverpool',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Manchester City',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea',
 'Chelsea']

In [17]:
X=player
X=X.astype(np.float32)

In [18]:
id=np.argwhere(np.isnan(X)) #尋找缺值的地方
id2=id[:,1] # 有那些feature還有missing value  # of missing:132 
id3=id[:,0] # 含missing value的player

In [19]:
id3.shape

(238,)

In [20]:
X[id3].shape

(238, 71)

In [21]:
np.unique(id2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
      dtype=int64)

In [22]:
X_del_miss=np.delete(X, id3, 0)   # delete players who have missing values #備用資料集

In [23]:
X_del_miss.shape

(421, 71)

#### 補值處理  by KNN

In [24]:
from sklearn.impute import KNNImputer
#X = [[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]]
imputer = KNNImputer(n_neighbors=11)

In [25]:
X_add_miss= imputer.fit_transform(X)

In [26]:
X_add_miss.shape

(532, 71)

In [27]:
X_add_miss[0].shape

(71,)

In [28]:
id_test=np.argwhere(np.isnan(X_add_miss))
id_test

array([], shape=(0, 2), dtype=int64)

In [35]:
np.save("X_add_miss_en.npy",X_add_miss)

### Create club dataset

In [29]:
def get_index(lst=None, item=''):
    return [index for (index,value) in enumerate(lst) if value == item]

In [30]:
id=get_index(player_team, 'Chelsea')

In [31]:
id

[2,
 3,
 4,
 5,
 6,
 8,
 9,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531]

In [32]:
len(player_team)

532

In [33]:
club_feature = np.zeros((1, 781))
for i in range(0,20):
    team_name=df_team.values[:,1][i]
    id_club = get_index(player_team, team_name) # 把屬於這個球隊的球員id找出來 # player_team是所有球員的對應球隊列表
    num = len(id_club)
    player_feature=np.zeros((1, 71))
    player_time_arr=np.zeros((num))
    for j in range(0,num):
        player_time_arr[j]=X_add_miss[id_club[j]][0]#
    idd =np.argsort([player_time_arr])#由小到大
    iddr = idd[::-1]
    ids = iddr[0][0:11] # select most important 11 players   #[0]
    nums = len(ids)
    for ii in range(0,nums):
        tmp=X_add_miss[ids[ii]]##<-------------------要改的是idclub
        tmp=tmp.reshape((1, 71))
        player_feature= np.column_stack((player_feature,tmp))
    #player_featurex= player_feature test
    tmpp=[i for i in range(71)]
    player_feature = np.delete(player_feature, tmpp)      # delete temporay row
    num_fe = len(player_feature)
    player_feature = player_feature.reshape((1, num_fe))
    if player_feature.shape[1]==781:
        #print("exe")
        club_feature= np.row_stack((club_feature,player_feature))
club_feature=np.delete(club_feature, 0, 0)     # delete temporay row

d = np.array([4,3,2,1])
d = np.pad(d,(0,5),'constant',constant_values=(0,0))
print(d)

In [34]:
club_feature.shape

(20, 781)

In [35]:
np.save("regression_X.npy",club_feature)

In [36]:
df_team.values[:,1]

array(['Manchester City', 'Manchester Utd', 'Liverpool', 'Chelsea',
       'Leicester City', 'West Ham', 'Tottenham', 'Arsenal',
       'Leeds United', 'Everton', 'Aston Villa', 'Newcastle Utd',
       'Wolves', 'Crystal Palace', 'Southampton', 'Brighton', 'Burnley',
       'Fulham', 'West Brom', 'Sheffield Utd'], dtype=object)

### 跳掉leeds united ,手動輸入控球率

In [37]:
Y=np.array([63.9,55.8,62.4,61.4,54.6,42.9,51.7,53.8,46.5,48.1,38.2,49.3,40.1,52.2,51.3,41.7,49.9,37.6,41.5])

In [38]:
Y.shape

(19,)

In [39]:
Y=Y.reshape((19, 1))

In [40]:
np.save("regression_Y.npy",Y)